import type { NextPage } from 'next'
import Head from 'next/head'
import AuthenticationByFacebook from '../components/Authentication/ByFacebook'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Learn Firebase</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='main'>
        <AuthenticationByFacebook />
      </main>
    </>
  )
}

export default Home
